version: '3.1'
services:
  phpmyadmin:
        depends_on:
          - mysql
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
          - 9000:80
        environment:
          PMA_HOST: mysql
          MYSQL_ROOT_PASSWORD: 123456
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 8306:3306